### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by h2soheili** [map-ir/mapir-mapbox#1]
BUILD SUCCESSFUL   => app crash on Screen Mount

"mapir-react-native-sdk": "^1.6.0",
 "react": "16.6.1",
 "react-native": "0.57.5"

dependencies {
     implementation project(':mapbox-react-native-mapbox-gl'){
          implementation ('com.squareup.okhttp3:okhttp:3.6.0') {
            force = true
        }
    }
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
    }
}

allprojects {
    repositories {
        // mavenLocal()
        jcenter()
        maven { url "$rootDir/../node_modules/react-native/android" }
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
}
task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**Comment by ReyhaneMasumi** [comment]
plz remove node_module folder and delete package-lock.json, then use "npm i" command.
Notice that versions are important! 
"dependencies": {
    "mapir-react-native-sdk": "^1.6.0",
    "react": "16.6.3",
    "react-native": "0.57.8"
}

**Comment by h2soheili** [comment]
i have tired react-native 0.55.4 0.57.5  0.57.8 0.59.5

stil same ,build success, app crashed.

**Comment by h2soheili** [comment]
implementation project(':mapbox-react-native-mapbox-gl'){
        implementation ('com.squareup.okhttp3:okhttp:3.6.0') {
            force = true
        }
    }
didnt work

**Comment by ReyhaneMasumi** [comment]
plz send us errors you've seen in log cat and the source code of implementation of Mapir module.

**Comment by h2soheili** [comment]
please build example project and commit .probably your repo have a bug . i have installed native MapBox and build success  works

**Comment by ReyhaneMasumi** [comment]
We have been testing many times and there is no problem.  Please allow us to assist you by sending us the errors.  Without knowing them, we can not do anything.

**Comment by h2soheili** [comment]
> implementation project(':mapbox-react-native-mapbox-gl')
i tried  with  

    "mapir-mapbox": "^1.2.1",
    "mapir-react-native-sdk": "https://github.com/map-ir/mapir-react-native-sdk",
    "react": "16.6.3",
    "react-native": "0.57.8"
with 
implementation project(':mapbox-react-native-mapbox-gl') instead  and works.


thanks for this repo and works
