### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by HoseinAsadi** [map-ir/mapir-mapbox#10]
Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints

dependencies": {
"@react-native-community/async-storage": "^1.5.0",
        "mapir-react-native-sdk": "^1.7.1",
        "native-base": "^2.12.1",
        "react": "16.8.3",
        "react-leaflet": "^2.4.0",
        "react-native": "0.59.9",

}

**Comment by mojtabadarzi** [comment]
```
...    
"mapir-react-native-sdk": "^1.6.1",
"react": "16.6.3",
"react-native": "0.57.8",
....
```

change your **package.json** content .

**Comment by ReyhaneMasumi** [comment]
...
"mapir-react-native-sdk": "^1.7.1",
"react": "16.6.3",
"react-native": "0.57.8"
...
you should use these versions in package.json!
Please delete `node_module` folder and use `npm i` command after change versions!

**Comment by imanro86** [comment]
Update package json and Rebiuld them
