### ISSUE TITLE
how can i disable 3D view in map ?

### ISSUE THREAD

**Issue by mojtabadarzi** [map-ir/mapir-mapbox#11]
The map view changes when the user works with **two fingers** on the map
How to **disable** this feature?

**Comment by ReyhaneMasumi** [comment]
As you can see in documentation [here](https://github.com/map-ir/mapir-mapbox/blob/master/docs/MapView.md), there is a prop that called 'pitchEnabled' that has two available value: Enable and Disable!! This props is Enable as default! you can make it Disable!
