### ISSUE TITLE
how can i search location in an input , for example tehran and show me this on map ?

### ISSUE THREAD

**Issue by mojtabadarzi** [map-ir/mapir-mapbox#12]

**Comment by ReyhaneMasumi** [comment]
You should use our [search API](https://docs.map.ir/search/)!

**Comment by mojtabadarzi** [comment]
i don't understand not more of your doc !!
i write this code and got this **error** .
_what is wrong with it ? help me plz_

```
    _fetch = (e) => {
        console.log(e);
        fetch('https://map.ir/search' + '?key=' + 'WsLdHK46I5Wfr5xgI0ynjjyiw9Fyhydu' + '&q='+  e, {
            method: 'GET',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        }).then((response) => {
            console.log(response)
            error.message
        })
    }
```

```
<TextInput
   placeholderTextColor={'#999'}
   placeholder="جستجو"
   style={styles.price_input}
   onChangeText={(e) => this._fetch(e)}
/>
```



_headers: Headers
map:
access-control-allow-origin: "*"
cache-control: "no-cache, private"
connection: "keep-alive"
content-type: "application/json"
date: "Sun, 30 Jun 2019 13:48:44 GMT"
server: "openresty"
transfer-encoding: "chunked"
x-powered-by: "PHP/7.2.18"
__proto__: Object
__proto__: Object
ok: false
status: **405**
statusText: undefined
type: "default"
url: "https://map.ir/search?key=WsLdHK46I5Wfr5xgI0ynjjyiw9Fyhydu&q=a"
_bodyInit: "{"status":405,"message":"Method Not Allowed","code":100110}"
_bodyText: "{"status":405,"message":"Method Not Allowed","code":100110}"
__proto__: Object_

**Comment by ReyhaneMasumi** [comment]
request method is POST!!!!You used GET method!Please pay attention to doc!

**Comment by Moji0098** [comment]
i use this function but i have an error : 
... ... ...
   ```
 componentWillUnmount() {
      this._fetch()
    }

_fetch = async () => {
        const url = 'https://map.ir/search';
        let data = new FormData();
        data.append("text","میدان آزادی");
        data.append("$select","roads,poi");
        data.append("$filter","province eq تهران");
        data.append("location","000000");
        data.append("type","Point");
        data.append("coordinates",  [
              51.3361930847168,
              35.7006311416626
            ]
           ); 

       
        await fetch(url , {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'multipart/form-data',
                'x-api-key' : 'WsLdHK46I5Wfr5xgI0ynjjyiw9Fyhydu'
            },
            body : data
        }).then((response) => {
            console.log(response)
            error.message
        }).catch((error) => {
            console.error(error);
        })
    }
```
**ERROR :** 

_TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (whatwg-fetch.js:504)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:580)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:394)
    at XMLHttpRequest.js:507
    at RCTDeviceEventEmitter.emit (EventEmitter.js:190)
    at MessageQueue.__callFunction (MessageQueue.js:349)
    at MessageQueue.js:106
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:105)_
