### ISSUE TITLE
SymbolLayer has not added into 'Mapir' component

### ISSUE THREAD

**Issue by c0mm4nDer** [map-ir/mapir-mapbox#15]
Hi 
 
SymbolLayer is a key component for shewn custom icon as a marker on the map.
plz add it into your next push.

**Comment by c0mm4nDer** [comment]
Moved to [here](https://github.com/map-ir/mapir-react-native-sdk/issues/11)

**Comment by ReyhaneMasumi** [comment]
SymbolLayer is added to SDK version 2.1.1.
please upgrade and enjoy it https://github.com/map-ir/mapir-mapbox/blob/master/docs/SymbolLayer.md.
thanks for your patient!
