### ISSUE TITLE
Support for Gradle Plugin version 3.3.1 

### ISSUE THREAD

**Issue by toooldmohammad** [map-ir/mapir-mapbox#3]
i have this bug
https://github.com/react-navigation/react-navigation/issues/5751

fix in:
https://github.com/nitaliano/react-native-mapbox-gl/issues/1511#issuecomment-473885457

please update to new master branch of mapbox

**Comment by hamid** [comment]
please see it and test it: #7

**Comment by ReyhaneMasumi** [comment]
thanks for your attention!
upgrade is in progress!
