### ISSUE TITLE
> Task :mapbox-react-native-mapbox-gl:compileDebugRenderscript FAILED  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by mojtabadarzi** [map-ir/mapir-mapbox#4]
* What went wrong:
Could not resolve all files for configuration ':mapbox-react-native-mapbox-gl:debugCompileClasspath'.
> Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
  Required by:
      project :mapbox-react-native-mapbox-gl
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.facebook.react:react-native:0.59.8' --> 'com.squareup.okhttp3:okhttp:3.12.1'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.2' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.facebook.react:react-native:0.59.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.facebook.react:react-native:0.59.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.12.1' --> 'com.squareup.okhttp3:okhttp:3.12.1'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9' --> 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.10' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization:0.1.0' --> 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.2' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9' --> 'com.mapbox.mapboxsdk:mapbox-java-services:2.2.9' --> 'com.squareup.retrofit2:retrofit:2.2.0' --> 'com.squareup.okhttp3:okhttp:3.6.0'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9' --> 'com.mapbox.mapboxsdk:mapbox-java-services:2.2.9' --> 'com.squareup.okhttp3:logging-interceptor:3.6.0' --> 'com.squareup.okhttp3:okhttp:3.6.0'
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.10.0' because of the following reason: debugRuntimeClasspath uses version 3.10.0
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.10.0' because of the following reason: debugRuntimeClasspath uses version 3.10.0
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.10.0' because of the following reason: debugRuntimeClasspath uses version 3.10.0
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.10.0' because of the following reason: debugRuntimeClasspath uses version 3.10.0

> Could not resolve com.squareup.okio:okio:1.14.0.
  Required by:
      project :mapbox-react-native-mapbox-gl
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.facebook.react:react-native:0.59.8' --> 'com.squareup.okio:okio:1.15.0'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.facebook.react:react-native:0.59.8' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okio:okio' strictly '1.14.0' because of the following reason: debugRuntimeClasspath uses version 1.14.0
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okio:okio' strictly '1.14.0' because of the following reason: debugRuntimeClasspath uses version 1.14.0
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okio:okio' strictly '1.14.0' because of the following reason: debugRuntimeClasspath uses version 1.14.0
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.squareup.okio:okio' strictly '1.14.0' because of the following reason: debugRuntimeClasspath uses version 1.14.0

> Could not resolve com.android.support:appcompat-v7:27.0.2.
  Required by:
      project :mapbox-react-native-mapbox-gl
   > Cannot find a version of 'com.android.support:appcompat-v7' that satisfies the version constraints: 
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.facebook.react:react-native:0.59.8' --> 'com.android.support:appcompat-v7:28.0.0'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9' --> 'com.android.support:appcompat-v7:25.4.0'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization:0.1.0' --> 'com.android.support:appcompat-v7:27.0.2'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.3.0' --> 'com.android.support:appcompat-v7:27.0.2'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9' --> 'com.mapzen.android:lost:3.0.4' --> 'com.android.support:appcompat-v7:25.3.1'
        Dependency path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9' --> 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.10' --> 'com.android.support:appcompat-v7:25.4.0'
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.0.2' because of the following reason: debugRuntimeClasspath uses version 27.0.2
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.0.2' because of the following reason: debugRuntimeClasspath uses version 27.0.2
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.0.2' because of the following reason: debugRuntimeClasspath uses version 27.0.2
        Constraint path 'vilaappOwner:mapbox-react-native-mapbox-gl:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.0.2' because of the following reason: debugRuntimeClasspath uses version 27.0.2
..
.
.
.
 be continue ...

after i add somthing for android and run android got this error ,, HELP me Please ..

**Comment by ReyhaneMasumi** [comment]
Mapbox doesn't support react-native>=58. So, please downgrade react-native to 0.57.8.
please use these versions:
{
"mapir-react-native-sdk": "^1.7.1",
    "react": "16.6.3",
    "react-native": "0.57.8"
}
sdkVersion: 28

**Comment by Moji0098** [comment]
i did that work but  i got same error :(

**Comment by mojtabadarzi** [comment]
i did this work , but i still have this err , 
i replace this
>  implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9'   

instead 

> implementation project(':mapbox-react-native-mapbox-gl')

and previous err destroyed but i got another err , 

/home/x/Desktop/vilaappOwner/android/app/src/main/java/com/vilaappowner/MainApplication.java:11: error: package com.mapbox.rctmgl does not exist
import com.mapbox.rctmgl.RCTMGLPackage;
                        ^
/home/x/Desktop/vilaappOwner/android/app/src/main/java/com/vilaappowner/MainApplication.java:29: error: cannot find symbol
          new RCTMGLPackage()
              ^
  symbol: class RCTMGLPackage
2 errors

FAILURE: Build failed with an exception.

**Comment by ReyhaneMasumi** [comment]
please follow the instruction: https://github.com/map-ir/mapir-mapbox/blob/master/android/install.md

**Comment by mojtabadarzi** [comment]
i did it , but didnt work

**Comment by ReyhaneMasumi** [comment]
if you used the specific versions and follow the instruction, bugs will be disappear!!
