### ISSUE TITLE
Is it possible for the user to select a spatial range for example by a range slider for himself and specify a circle or square on the map?

### ISSUE THREAD

**Issue by mojtabadarzi** [map-ir/mapir-mapbox#8]

**Comment by ReyhaneMasumi** [comment]
its special feature for your application! you can test it to see how it is working! we have no limitation in this case!

**Comment by mojtabadarzi** [comment]
do you have any idea for this feature ?

**Comment by ReyhaneMasumi** [comment]
Your question is not about our SDK! so i'm sorry and wish you luck!
